sudo: false
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-7

script:
  - cd ./KLM_lib/build
  - cmake ..
  - cmake --build . -- -j2